export const merchant = {
  franchise_id: { key: 'franchiseId', label: '加盟店ID' },
  franchise_type: { key: 'franchiseType', label: '加盟店種別' },
  agent_id: { key: 'agentId', label: '代理店ID' },
  business_type: { key: 'businessType', label: '業種' },
  store_number: { key: 'storeNumber', label: '届出番号' },
  franchise_name: { key: 'franchiseName', label: '加盟店名' },
  legal_name: { key: 'legalName', label: '法人名' },
  representative_name: { key: 'representativeName', label: '代表者名' },
  representative_phone: { key: 'representativePhone', label: '代表者電話番号' },
  representative_email: {
    key: 'representativeEmail',
    label: '代表者メールアドレス',
  },
  manager_name: { key: 'managerName', label: '担当者名' },
  manager_phone: { key: 'managerPhone', label: '担当者電話番号' },
  manager_email: { key: 'managerEmail', label: '担当者メールアドレス' },
  postal_code: { key: 'postalCode', label: '郵便番号' },
  prefecture: { key: 'prefecture', label: '都道府県' },
  city: { key: 'city', label: '市区町村' },
  street_address: { key: 'streetAddress', label: '町域・番地' },
  building_name: { key: 'buildingName', label: '建物名・部屋番号' },
  bank_id: { key: 'bankId', label: '銀行ID' },
  branch_id: { key: 'branchId', label: '支店ID' },
  account_type: { key: 'accountType', label: '口座種類' },
  account_number: { key: 'accountNumber', label: '口座番号' },
  account_holder: { key: 'accountHolder', label: '口座名義人' },
  status: { key: 'status', label: 'ステイタス' },
  attached_files: { key: 'attachedFiles', label: '添付ファイル' },
  registration_date: { key: 'registrationDate', label: '登録日' },
  update_date: { key: 'updateDate', label: '更新日' },
  deletion_date: { key: 'deletionDate', label: '削除日' },
  agent_name: { key: 'agentName', label: '代理店名' },
};

export const product = {
  products_id: { key: 'productsId', label: '商品ID' },
  franchise_id: { key: 'franchiseId', label: '加盟店ID' },
  product_name: { key: 'productName', label: '商品名' },
  product_type: { key: 'productType', label: '商品区分' },
  description: { key: 'description', label: '商品説明' },
  price: { key: 'price', label: '商品価格' },
  status: { key: 'status', label: 'ステイタス' },
  registration_date: { key: 'registrationDate', label: '登録日' },
  update_date: { key: 'updateDate', label: '更新日' },
  deletion_date: { key: 'deletionDate', label: '削除日' },
  price_from: { key: 'priceFrom', label: '商品価格' },
  price_to: { key: 'priceTo', label: '商品価格' },
  options: { key: 'options', label: 'オプション' },
  products_image: { key: 'productsImage', label: '商品画像' },
};

export const productOption = {
  order_id: { key: 'orderId', label: '注文ID' },
  products_id: { key: 'productsId', label: '商品ID' },
  option_id: { key: 'optionId', label: 'オプション商品ID' },
  product_name: { key: 'productName', label: 'オプション商品名' },
  product_type: { key: 'productType', label: 'オプション商品区分' },
  description: { key: 'description', label: 'オプション商品説明' },
  price: { key: 'price', label: 'オプション商品価格' },
  registration_date: { key: 'registrationDate', label: '登録日' },
  update_date: { key: 'updateDate', label: '更新日' },
  deletion_date: { key: 'deletionDate', label: '削除日' },
};

export const user = {
  user_id: { key: 'userId', label: 'ユーザーID' },
  user_name: { key: 'userName', label: 'ユーザー名' },
  email: { key: 'email', label: 'メールアドレス' },
  password: { key: 'password', label: 'パスワード' },
  status: { key: 'status', label: 'ステイタス' },
  registration_date: { key: 'registrationDate', label: '登録日' },
  update_date: { key: 'updateDate', label: '更新日' },
  deletion_date: { key: 'deletionDate', label: '削除日' },
  role: { key: 'role', label: '役割' },
};

export const settlement = {
  settlement_id: { key: 'settlementId', label: '決済ID' },
  settlement_type: { key: 'settlementType', label: '決済区分' },
  settlement_time: { key: 'settlementTime', label: '決済日時' },
  franchise_id: { key: 'franchiseId', label: '加盟店ID' },
  order_id: { key: 'orderId', label: '注文ID' },
  user_id: { key: 'userId', label: '利用者ID' },
  settlement_amount: { key: 'settlementAmount', label: '金額' },
  settlement_amount_from: { key: 'settlementAmountFrom', label: '金額' },
  settlement_amount_to: { key: 'settlementAmountTo', label: '金額' },
  status: { key: 'status', label: '決済ステイタス' },
  registration_date: { key: 'registrationDate', label: '登録日' },
  update_date: { key: 'updateDate', label: '更新日' },
  deletion_date: { key: 'deletionDate', label: '削除日' },
  franchise_name: { key: 'franchiseName', label: '加盟店名' },
  product_name: { key: 'productName', label: '商品名' },
  product_price: { key: 'productPrice', label: '商品金額' },
  error_code: { key: 'errorCode', label: 'エラーコード' },
  error_message: { key: 'errorMessage', label: 'エラー内容' },
};
